spring:
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.testkafka.workers"
logging:
  level:
    root: error
    com.example: info