spring:
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
logging:
  level:
    root: error
    com.example: info